// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"net/netip"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Role struct {
	ID          int64
	Name        string
	Description pgtype.Text
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type User struct {
	ID                         uuid.UUID
	Email                      string
	PasswordHash               string
	Username                   pgtype.Text
	FirstName                  pgtype.Text
	LastName                   pgtype.Text
	FullName                   pgtype.Text
	PhoneNumber                pgtype.Text
	DateOfBirth                pgtype.Date
	AvatarUrl                  pgtype.Text
	IsActive                   bool
	IsVerified                 bool
	IsDeleted                  bool
	EmailVerifiedAt            pgtype.Timestamptz
	VerificationToken          pgtype.Text
	VerificationTokenExpiresAt pgtype.Timestamptz
	ResetToken                 pgtype.Text
	ResetTokenExpiresAt        pgtype.Timestamptz
	LastLoginAt                pgtype.Timestamptz
	LastLoginIp                *netip.Addr
	FailedLoginAttempts        pgtype.Int4
	LockedUntil                pgtype.Timestamptz
	TwoFactorEnabled           bool
	TwoFactorSecret            pgtype.Text
	Timezone                   pgtype.Text
	Language                   pgtype.Text
	Metadata                   []byte
	CreatedAt                  pgtype.Timestamptz
	UpdatedAt                  pgtype.Timestamptz
	DeletedAt                  pgtype.Timestamptz
}

type UserRole struct {
	UserID     uuid.UUID
	RoleID     int64
	AssignedAt pgtype.Timestamptz
	AssignedBy pgtype.UUID
	ExpiresAt  pgtype.Timestamptz
}
